export const usersConfig = {
  resource: 'users',
  pagination: {
    enabled: true,
    itemsPath: 'items',
    totalPath: 'total',
    pagePath: 'page',
  },
  fields: [
    {
      name: 'name',
      label: 'Name',
      input: 'text',
      component: 'ArchInput',
      required: false,
      nullable: false,
      validation: {},
    },
    {
      name: 'email',
      label: 'Email',
      input: 'email',
      component: 'ArchInput',
      required: true,
      nullable: false,
      validation: {},
    },
    {
      name: 'status',
      label: 'Status',
      input: 'select',
      component: 'ArchSelect',
      required: false,
      nullable: false,
      enumValues: ['active', 'blocked', 'pending'],
      hint: 'User lifecycle status',
      validation: {},
    },
    {
      name: 'age',
      label: 'Age',
      input: 'number',
      component: 'ArchInput',
      required: false,
      nullable: true,
      validation: {
        minimum: 18,
        maximum: 120,
      },
    },
    {
      name: 'verified',
      label: 'Verified',
      input: 'switch',
      component: 'ArchSwitch',
      required: false,
      nullable: false,
      hint: 'Whether the user confirmed their email',
      validation: {},
    },
    {
      name: 'password',
      label: 'Password',
      input: 'password',
      component: 'ArchInput',
      required: false,
      nullable: false,
      validation: {
        minLength: 12,
      },
    },
    {
      name: 'profile',
      label: 'Profile',
      input: 'text',
      component: 'ArchInput',
      required: false,
      nullable: false,
      validation: {},
    },
  ],
  columns: [
    {
      name: 'id',
      label: 'Id',
      cell: 'text',
      sortable: true,
      nullable: false,
    },
    {
      name: 'name',
      label: 'Name',
      cell: 'text',
      sortable: true,
      nullable: false,
    },
    {
      name: 'email',
      label: 'Email',
      cell: 'text',
      sortable: true,
      nullable: false,
    },
    {
      name: 'status',
      label: 'Status',
      cell: 'badge',
      sortable: true,
      nullable: false,
      hint: 'User lifecycle status',
    },
    {
      name: 'age',
      label: 'Age',
      cell: 'number',
      sortable: true,
      nullable: true,
    },
    {
      name: 'verified',
      label: 'Verified',
      cell: 'boolean',
      sortable: false,
      nullable: false,
      hint: 'Whether the user confirmed their email',
    },
    {
      name: 'createdAt',
      label: 'Created At',
      cell: 'dateTime',
      sortable: true,
      nullable: false,
    },
    {
      name: 'profile',
      label: 'Profile',
      cell: 'json',
      sortable: false,
      nullable: false,
    },
  ],
} as const
