export const reportsConfig = {
  resource: 'reports',
  pagination: {
    enabled: true,
    itemsPath: 'items',
    totalPath: 'total',
    pagePath: 'page',
  },
  fields: [
    {
      name: 'title',
      label: 'Title',
      input: 'text',
      component: 'ArchInput',
      required: true,
      nullable: false,
      validation: {},
    },
    {
      name: 'status',
      label: 'Status',
      input: 'select',
      component: 'ArchSelect',
      required: true,
      nullable: false,
      enumValues: ['ready', 'processing', 'failed'],
      validation: {},
    },
    {
      name: 'generatedAt',
      label: 'Generated At',
      input: 'dateTime',
      component: 'ArchDatePicker',
      required: true,
      nullable: false,
      validation: {},
    },
    {
      name: 'owner',
      label: 'Owner',
      input: 'text',
      component: 'ArchInput',
      required: false,
      nullable: false,
      validation: {},
    },
    {
      name: 'rows',
      label: 'Rows',
      input: 'number',
      component: 'ArchInput',
      required: false,
      nullable: false,
      validation: {
        minimum: 0,
      },
    },
  ],
  columns: [
    {
      name: 'id',
      label: 'Id',
      cell: 'text',
      sortable: true,
      nullable: false,
    },
    {
      name: 'title',
      label: 'Title',
      cell: 'text',
      sortable: true,
      nullable: false,
    },
    {
      name: 'status',
      label: 'Status',
      cell: 'badge',
      sortable: true,
      nullable: false,
    },
    {
      name: 'generatedAt',
      label: 'Generated At',
      cell: 'dateTime',
      sortable: true,
      nullable: false,
    },
    {
      name: 'owner',
      label: 'Owner',
      cell: 'text',
      sortable: true,
      nullable: false,
    },
    {
      name: 'rows',
      label: 'Rows',
      cell: 'number',
      sortable: true,
      nullable: false,
    },
  ],
} as const
