export const ordersConfig = {
  resource: 'orders',
  pagination: {
    enabled: true,
    itemsPath: 'items',
    totalPath: 'total',
    pagePath: 'page',
  },
  fields: [
    {
      name: 'number',
      label: 'Number',
      input: 'text',
      component: 'ArchInput',
      required: true,
      nullable: false,
      validation: {},
    },
    {
      name: 'status',
      label: 'Status',
      input: 'select',
      component: 'ArchSelect',
      required: true,
      nullable: false,
      enumValues: ['draft', 'paid', 'shipped'],
      validation: {},
    },
    {
      name: 'total',
      label: 'Total',
      input: 'number',
      component: 'ArchInput',
      required: true,
      nullable: false,
      validation: {
        minimum: 0,
      },
    },
    {
      name: 'paid',
      label: 'Paid',
      input: 'switch',
      component: 'ArchSwitch',
      required: false,
      nullable: false,
      validation: {},
    },
    {
      name: 'dueDate',
      label: 'Due Date',
      input: 'date',
      component: 'ArchDatePicker',
      required: false,
      nullable: false,
      validation: {},
    },
    {
      name: 'customer',
      label: 'Customer',
      input: 'text',
      component: 'ArchInput',
      required: false,
      nullable: false,
      validation: {},
    },
  ],
  columns: [
    {
      name: 'id',
      label: 'Id',
      cell: 'text',
      sortable: true,
      nullable: false,
    },
    {
      name: 'number',
      label: 'Number',
      cell: 'text',
      sortable: true,
      nullable: false,
    },
    {
      name: 'status',
      label: 'Status',
      cell: 'badge',
      sortable: true,
      nullable: false,
    },
    {
      name: 'total',
      label: 'Total',
      cell: 'number',
      sortable: true,
      nullable: false,
    },
    {
      name: 'paid',
      label: 'Paid',
      cell: 'boolean',
      sortable: false,
      nullable: false,
    },
    {
      name: 'dueDate',
      label: 'Due Date',
      cell: 'date',
      sortable: true,
      nullable: false,
    },
    {
      name: 'customer',
      label: 'Customer',
      cell: 'json',
      sortable: false,
      nullable: false,
    },
  ],
} as const
